export const baklavaProducts = [
  {
    id: 'twin-baklava',
    name: 'Twin Baklava',
    sub: 'Box of 12',
    price: 42,
    imageSrc: '/baklava/twin-baklava.png',
    imageWidth: 496,
    imageHeight: 472,
  },
  {
    id: '48-piece-tray',
    name: '48 Piece Tray',
    sub: 'Single tray',
    price: 53,
    imageSrc: '/baklava/48-piece-tray.png',
    imageWidth: 1157,
    imageHeight: 655,
  },
  {
    id: '6-piece-treats',
    name: '6 Piece Treats',
    sub: 'Box of 9',
    price: 47,
    imageSrc: '/baklava/6-piece-treats.png',
    imageWidth: 861,
    imageHeight: 384,
  },
  {
    id: '40-piece-tray',
    name: '40 Piece Tray',
    sub: 'Single tray',
    price: 53,
    imageSrc: '/baklava/40-piece-tray.png',
    imageWidth: 1149,
    imageHeight: 649,
  },
  {
    id: '9-piece-family',
    name: '9 Piece Family',
    sub: 'Box of 8',
    price: 62,
    imageSrc: '/baklava/9-piece-family.png',
    imageWidth: 735,
    imageHeight: 530,
  },
  {
    id: '90-piece-tray',
    name: '90 Piece Tray',
    sub: 'Single tray',
    price: 53,
    imageSrc: '/baklava/90-piece-tray.png',
    imageWidth: 1168,
    imageHeight: 668,
  },
];
